# Generated by Django 4.1.3 on 2022-11-13 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('execapi', '0002_accountable_user_voluntary_user_alter_phone_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountable',
            name='nome',
        ),
        migrations.AddField(
            model_name='accountable',
            name='institution',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='execapi.institution'),
        ),
    ]
