# Generated by Django 4.1.3 on 2022-11-13 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execapi', '0002_institution_address_alter_user_is_accountable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(default='', max_length=50, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='address',
            name='district',
            field=models.CharField(default='', max_length=50, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='address',
            name='number',
            field=models.IntegerField(default=0, verbose_name='Numero'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(default='', max_length=100, verbose_name='Rua'),
        ),
    ]
