# Generated by Django 4.1.3 on 2022-11-13 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('execapi', '0003_alter_address_city_alter_address_district_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='phone',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='user',
            name='phones',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='execapi.phone'),
        ),
        migrations.AlterField(
            model_name='address',
            name='lat',
            field=models.CharField(default='', max_length=20, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='address',
            name='long',
            field=models.CharField(default='', max_length=20, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(default='', max_length=50, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='address',
            name='zip',
            field=models.CharField(default='', max_length=20, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='email',
            field=models.CharField(default='', max_length=100, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo?'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone',
            field=models.CharField(default='', max_length=15, verbose_name='Numero'),
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('national_id', 'phones')},
        ),
        migrations.RemoveField(
            model_name='phone',
            name='user',
        ),
    ]
