# Generated by Django 4.1.3 on 2022-11-13 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execapi', '0005_alter_accountable_institution_attendence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendence',
            name='point',
        ),
        migrations.AddField(
            model_name='attendence',
            name='latitude',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='attendence',
            name='longitude',
            field=models.CharField(default='', max_length=15),
        ),
    ]
