# Generated by Django 4.1.3 on 2022-11-13 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('execapi', '0005_alter_user_options_alter_user_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Telefones',
        ),
        migrations.AddField(
            model_name='user',
            name='phones',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Telefones', to='execapi.phone'),
        ),
    ]
