# Generated by Django 4.1.3 on 2022-11-13 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('execapi', '0006_remove_user_telefones_user_phones'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('username', 'phones')},
        ),
    ]
