# Generated by Django 4.1.3 on 2022-11-13 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('execapi', '0007_alter_user_options_alter_user_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendence',
            name='institution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='execapi.institution'),
        ),
    ]
