# Generated by Django 4.1.3 on 2022-11-13 22:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('execapi', '0008_attendence_institution'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('national_id', 'is_voluntary')},
        ),
        migrations.AddField(
            model_name='phone',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='institution',
            name='email',
            field=models.CharField(default='', max_length=100, verbose_name='Email'),
        ),
        migrations.RemoveField(
            model_name='user',
            name='phones',
        ),
    ]
