# Generated by Django 4.1.3 on 2022-11-13 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execapi', '0011_alter_attendence_input_photo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='institution',
            name='address',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='user',
        ),
        migrations.AddField(
            model_name='institution',
            name='city',
            field=models.CharField(default='', max_length=50, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='institution',
            name='district',
            field=models.CharField(default='', max_length=50, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='institution',
            name='lat',
            field=models.CharField(default='', max_length=20, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='institution',
            name='long',
            field=models.CharField(default='', max_length=20, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='institution',
            name='number',
            field=models.IntegerField(default=0, verbose_name='Numero'),
        ),
        migrations.AddField(
            model_name='institution',
            name='phones',
            field=models.ManyToManyField(to='execapi.phone'),
        ),
        migrations.AddField(
            model_name='institution',
            name='state',
            field=models.CharField(default='', max_length=50, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='institution',
            name='street',
            field=models.CharField(default='', max_length=100, verbose_name='Rua'),
        ),
        migrations.AddField(
            model_name='institution',
            name='zip',
            field=models.CharField(default='', max_length=20, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='user',
            name='phones',
            field=models.ManyToManyField(to='execapi.phone'),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
