# Generated by Django 4.1.3 on 2022-11-13 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('execapi', '0012_alter_user_options_alter_user_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(default='', max_length=100, verbose_name='Rua')),
                ('number', models.IntegerField(default=0, verbose_name='Numero')),
                ('district', models.CharField(default='', max_length=50, verbose_name='Bairro')),
                ('city', models.CharField(default='', max_length=50, verbose_name='Cidade')),
                ('zip', models.CharField(default='', max_length=20, verbose_name='CEP')),
                ('state', models.CharField(default='', max_length=50, verbose_name='Estado')),
                ('lat', models.CharField(default='', max_length=20, verbose_name='Latitude')),
                ('long', models.CharField(default='', max_length=20, verbose_name='Longitude')),
            ],
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.RemoveField(
            model_name='institution',
            name='city',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='district',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='long',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='number',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='phones',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='state',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='street',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='zip',
        ),
        migrations.AddField(
            model_name='institution',
            name='phone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='execapi.phone'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='execapi.phone'),
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('national_id', 'phone')},
        ),
        migrations.RemoveField(
            model_name='user',
            name='phones',
        ),
        migrations.AddField(
            model_name='institution',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='execapi.address'),
        ),
    ]
