# Generated by Django 4.1.3 on 2022-11-13 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execapi', '0013_address_alter_user_options_remove_institution_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='voluntary',
            name='is_employed',
        ),
        migrations.RemoveField(
            model_name='voluntary',
            name='total_time_hours_work',
        ),
        migrations.AddField(
            model_name='phone',
            name='number',
            field=models.CharField(default='', max_length=15, verbose_name='Numero'),
        ),
        migrations.AlterField(
            model_name='voluntary',
            name='comments',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='institution',
            unique_together={('name', 'email'), ('name', 'phone'), ('name', 'address')},
        ),
    ]
