# Generated by Django 4.1.3 on 2022-11-13 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('execapi', '0014_remove_phone_phone_remove_voluntary_is_employed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institution',
            old_name='phone',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='phone',
            new_name='number',
        ),
        migrations.AlterUniqueTogether(
            name='institution',
            unique_together={('name', 'email'), ('name', 'address'), ('name', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('national_id', 'number')},
        ),
    ]
