# Generated by Django 4.1.3 on 2022-11-14 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('execapi', '0015_rename_phone_institution_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterField(
            model_name='institution',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='execapi.address', verbose_name='Endereco'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='execapi.phone', verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='user',
            name='number',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='execapi.phone'),
        ),
    ]
