# Generated by Django 4.1.3 on 2022-11-14 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('execapi', '0018_remove_user_number_phone_user_alter_phone_number_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Phone',
            new_name='PhoneUser',
        ),
        migrations.AlterUniqueTogether(
            name='institution',
            unique_together={('name', 'address'), ('name', 'email'), ('email', 'address')},
        ),
        migrations.CreateModel(
            name='PhoneInstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=15, unique=True, verbose_name='Numero')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('institution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='execapi.institution')),
            ],
        ),
        migrations.RemoveField(
            model_name='institution',
            name='number',
        ),
    ]
