# Generated by Django 4.1.3 on 2022-11-14 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('execapi', '0019_rename_phone_phoneuser_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phoneinstitution',
            options={'verbose_name_plural': 'Institutions Phones'},
        ),
        migrations.AlterModelOptions(
            name='phoneuser',
            options={'verbose_name_plural': 'Users Phones'},
        ),
    ]
