# Generated by Django 4.1.3 on 2022-11-14 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execapi', '0020_alter_phoneinstitution_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='commments',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='attendence',
            name='latitude',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='attendence',
            name='longitude',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='address',
            unique_together={('lat', 'long')},
        ),
    ]
